export const SET_LOADING = 'SET_LOADING';
export const SET_TOAST = 'SET_TOAST';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const PAGINATION_SET_PAGE = 'PAGINATION_SET_PAGE';
